### ISSUE TITLE
question about CSR privilege 

### ISSUE THREAD

**Issue by PorterLu** [MaxXSoft/Fuxi#3]
I am confused that the csr register does not need to check the privilege level when writing, but when reading. This is what I read in CsrFile.scala, Am I understanding it wrong?

**Comment by MaxXSoft** [comment]
Yes, it may not seem so intuitive.

In ALU stage, if a CSR instruction is being executed, either to read or write the CSR, the core will send a request through the CSR read channel:

https://github.com/MaxXSoft/Fuxi/blob/457420d200cd8aade4b6976a1f364f5541656db1/src/main/scala/core/ALU.scala#L55-L60

The CSR file will check if the CSR specified by the read channel is readable/writable, and if it can be accessed at the current privilege level:

https://github.com/MaxXSoft/Fuxi/blob/5548a4988f9ccbfc6af56a36570576716d7b79df/src/main/scala/csr/CsrFile.scala#L135-L143

If the given CSR cannot be accessed, the ALU stage will generate an illegal instruction exception, which will be handled in the MEM stage.

**Comment by PorterLu** [comment]
thanks for generously giving your time, bro.  I seem to understand a little.

**Comment by PorterLu** [comment]
I'm still stuck on this issue, "writeEn" only depends on  io.write.op. `  when (writeEn) {` at line 214 ，which excutes before trapping. The CSR register will be modified in advance，shouldn't exceptions and interrupts be handled first?

**Comment by MaxXSoft** [comment]
> "writeEn" only depends on io.write.op.

That's true.

> which excutes before trapping.

Not true.

You are focusing on the `CsrFile` module, which is just a module that handles the CSR access requests and holds the actual data of all CSRs. However, the trap handling process takes place outside of the module.

In stage `Decode`, `ALU` and `Mem`, exception information will be generated, and CSRs will be read if needed. In `Mem` stage, which is the last stage before writing back, all exception should be handled, otherwise the exception instruction will affect the processor state. Finally, in `WriteBack` stage, if there is a CSR write instruction to be committed, the corresponding CSR will be changed.

If `Mem` stage raises an exception, the `PipelineController` module will flush all pipeline stages, and nothing will be written back, including CSR data. Therefore, `writeEn` and `io.except.hasTrap` will not both be true in `CsrFile`.

**Comment by PorterLu** [comment]
Your explanation is very inspiring. I implemented the pipeline in a similar way, but exceptions will be processed as soon as it is detected. And there may be another reason to write to the `CSR` register first，we have to ensure atomicity of CSR, which means 
we need to finish executing the `CSR` instruction even if the interrupt comes.  
Finally, thank you again for your selfless help.
